### ISSUE TITLE
No such file or directory: 'm2h2.pkl'

### ISSUE THREAD

**Issue by wenxiong-xu** [declare-lab/M2H2-dataset#1]
This work is interesting but the file 'm2h2.pkl' doesn't exsit.  Also, the model 'bcLSTM' is missing.

**Comment by DushyantChauhan** [comment]
Hello,

I have updated the readme file. Also, you can download the m2h2.pkl file
from here
https://drive.google.com/file/d/1TFtoJMAPYoJdnXKsQpNgGXU3rSSMell6/view?usp=sharing

Also, we will update this file by today.

if you need anything please free to contact me.

Thank you.


Regards,
Dushyant Singh Chauhan
-------------------------------------------------------------
PhD Scholar, Dept. of CSE,
Indian Institute of Technology, Patna,
Ph: +91-9720162666
Work-email: ***@***.***
Alternate-email: ***@***.***
Skype: 9720162666
